require:
  - rubocop-rspec

AllCops:
  Exclude:
    - 'Guardfile'
  NewCops: enable
  TargetRubyVersion: 3.2

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 160

Metrics/AbcSize:
  Max: 20

Metrics/CyclomaticComplexity:
  Max: 8

Style/Documentation:
  Enabled: false

RSpec/ExampleLength:
  Max: 25

RSpec/MessageChain:
  Enabled: false

RSpec/MessageSpies:
  EnforcedStyle: receive

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/NestedGroups:
  Max: 4

RSpec/StubbedMock:
  Enabled: false